# Generated by Django 4.2.3 on 2023-07-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0003_product_video_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="video_url",
        ),
    ]
