# Generated by Django 4.2.3 on 2023-07-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0005_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="video_url",
        ),
    ]
