# Generated by Django 4.2.3 on 2023-07-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0007_video_video_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Video",
        ),
    ]
