# Generated by Django 4.2.3 on 2023-07-12 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0008_delete_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="video_file",
            field=models.FileField(
                blank=True,
                upload_to="video_files/",
                validators=[
                    django.core.validators.FileExtensionValidator(["mp4", "mov"])
                ],
            ),
        ),
    ]
