# Generated by Django 4.2.3 on 2023-07-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0009_product_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="payment_status",
            field=models.BooleanField(default=False),
        ),
    ]
