# Generated by Django 4.2.3 on 2023-07-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0010_product_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
