# Generated by Django 4.2.3 on 2023-07-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0011_product_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="payment_status",
            field=models.BooleanField(default=False),
        ),
    ]
