# Generated by Django 4.2.3 on 2023-07-19 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0017_product_user_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="user_profile",
        ),
    ]
