# Generated by Django 4.2.3 on 2023-07-19 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0022_remove_product_user_product_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchased_products",
                to="newapp.userprofile",
            ),
        ),
    ]
