# Generated by Django 4.2.3 on 2023-07-19 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0023_alter_product_user_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="product",
            name="user_profile",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="payment_status",
        ),
        migrations.CreateModel(
            name="PurchasedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_status", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="newapp.product"
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newapp.userprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_profile", "product")},
            },
        ),
    ]
