# Generated by Django 4.2.3 on 2023-07-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0024_remove_product_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics"),
        ),
    ]
